---
- name: Set locale to UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Configure locale package env locale
  debconf:
    name: locales
    question: 'locales/default_environment_locale'
    value: n_US.UTF-8
    vtype: 'select'

- name: Install base packages
  apt:
    name: [
      'ntp',
      'vim',
      'curl',
      'wget',
      'build-essential',
      'software-properties-common',
      'git',
      'ubuntu-keyring',
      'ca-certificates',
      'apt-transport-https',
      'python-pymysql'
    ]
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Start time services
  service: name=systemd-timesyncd state=started enabled=yes
  become: yes

- name: Run timedatectl status
  command: /usr/bin/timedatectl status
  changed_when: False
  check_mode: no
  register: timedatectl_result

- name: Set timezone
  command: /usr/bin/timedatectl set-timezone Europe/Tallinn
  when: "'Europe/Tallinn' not in timedatectl_result.stdout"
  become: yes

- name: Enable ntp
  command: /usr/bin/timedatectl set-ntp true
  when: "'Network time on: no' in timedatectl_result.stdout"
  become: yes

