- name: init Local sens. cabal
  command: cabal sandbox init
  args:
    chdir: /vagrant_data/pleak-sql-analysis/globalsensitivity-cabal/
    creates: /vagrant_data/pleak-sql-analysis/globalsensitivity-cabal/cabal.sandbox.config
  register: result

- name: cabal update
  command: cabal update
  args:
    chdir: /vagrant_data/pleak-sql-analysis/globalsensitivity-cabal/
  when: result.changed

- name: cabal install happy
  command: cabal install happy
  args:
    chdir: /vagrant_data/pleak-sql-analysis/globalsensitivity-cabal/
  when: result.changed

- name: cabal install --only-dependencies
  command: cabal install --only-dependencies
  args:
    chdir: /vagrant_data/pleak-sql-analysis/globalsensitivity-cabal/

- name: cabal conf
  command: cabal configure
  args:
    chdir: /vagrant_data/pleak-sql-analysis/globalsensitivity-cabal/

- name: cabal build
  command: cabal build
  args:
    chdir: /vagrant_data/pleak-sql-analysis/globalsensitivity-cabal/
