- name: install haskell stack
  apt:
    name: [
      z3,
      cabal-install,
      ghc,
      postgresql,
      postgresql-contrib,
      libpq-dev,
      python-psycopg2
    ]
    state: present
    update_cache: yes
    force_apt_get: yes

- include_tasks: global-sensitivity.yml
- include_tasks: local-sensitivity.yml
- include_tasks: derivative-sensitivity.yml
