- name: install deps
  apt:
    name: [
      z3,
      m4,
      ocaml,
      ocamlbuild,
      opam,
      libocamlgraph-ocaml-dev,
      libxml-light-ocaml-dev,
      libyojson-ocaml-dev,
      ocaml-findlib
    ]
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Build
  shell: ocamlbuild -use-ocamlfind GrbDriver.native
  args:
    chdir: /vagrant_data/pleak-leaks-when-analysis/src

- name: Build
  shell: ocamlbuild -use-ocamlfind GrbDriver.native
  args:
    chdir: /vagrant_data/pleak-leaks-when-ast-transformation/pleak-leaks-when-analysis/src

- name: add apt key for nodesource
  apt_key:
    url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'

- name: add repo for nodesource
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_12.x bionic main'
    update_cache: yes

- name: install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes
    force_apt_get: yes

- name: create frontend service
  copy:
    src: 'etc/systemd/system/pleak-leakswhen.service'
    dest: '/etc/systemd/system/pleak-leakswhen.service'

- name: Running NPM install
  npm:
    unsafe_perm: yes
    path: '/vagrant_data/pleak-leaks-when-ast-transformation'

- name: Enable and start frontend service
  systemd:
    name: pleak-leakswhen
    enabled: no
    state: stopped

