- name: install java, maven
  apt:
    name: [
      openjdk-8-jdk,
      maven
    ]
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Correct java version selected
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/bin/java

- name: check if db init
  shell: mysql -e 'SHOW DATABASES;'| grep pleak
  register: result
  failed_when: result.rc == 2

- name: Run db setup
  shell: mysql -u root < src/main/resources/db/setup.sql
  args:
    chdir: /vagrant_data/pleak-backend/
  when: result.rc == 1

- name: Run migrations
  command: mvn flyway:migrate
  args:
    chdir: /vagrant_data/pleak-backend/

- name: Run db devusers
  shell: mysql -u root < src/main/resources/db/dev.sql
  args:
    chdir: /vagrant_data/pleak-backend/
  when: result.rc == 1

- name: create backend service
  copy:
    src: 'etc/systemd/system/pleak-backend.service'
    dest: '/etc/systemd/system/pleak-backend.service'

- name: Create folder for backend logs
  file: name=/vagrant_data/pleak-backend/log state=directory

- name: build backend application
  command: mvn install
  args:
    chdir: /vagrant_data/pleak-backend/

- name: Enable and start backend service
  systemd:
    name: pleak-backend
    enabled: no
    state: stopped

- name: add mcrl2 repo
  apt_repository:
    repo: ppa:mcrl2/release-ppa

- name: mcrl2
  apt:
    name: mcrl2
    state: present
    update_cache: yes
    force_apt_get: yes

- name: install postgres stack
  apt:
    name: [
      postgresql,
      postgresql-contrib,
      libpq-dev,
    ]
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Create a new database with name "banach"
  become: true
  become_user: postgres
  postgresql_db:
    name: ga_propagation

- name:
  become: true
  become_user: postgres
  postgresql_user:
    db: ga_propagation
    name: ga_propagation
    password: ceec4eif7ya
    priv: ALL


- name: Add postgres cube extension
  become: true
  become_user: postgres
  postgresql_ext:
    name: cube
    db: ga_propagation

- name: Add postgres earthdistance extension
  become: true
  become_user: postgres
  postgresql_ext:
    name: earthdistance
    db: ga_propagation
